name:                Fukami
version:             0.1.0.0
github:              "llbxg/Fukami"
license:             BSD3
author:              "kosh"
maintainer:          ""
copyright:           "2020 kosh"

extra-source-files:
- README.md
- ChangeLog.md

description:         Please see the README on GitHub at <https://github.com/llbxg/Fukami#readme>

dependencies:
- base >= 4.7 && < 5
- hmatrix
- random
- bytestring
- time

library:
  source-dirs: src

executables:
  Fukami-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - Fukami

tests:
  Fukami-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - Fukami